# Generated by Django 5.0.3 on 2024-03-17 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0003_rename_sick_tashxis_diagnoz_tashxis_tashxis'),
        ('User', '0002_alter_bemor_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tashxis',
            name='user',
        ),
        migrations.AlterField(
            model_name='tashxis',
            name='bemor',
            field=models.ForeignKey(default='uchirilgan bemor', on_delete=django.db.models.deletion.SET_DEFAULT, to='User.bemor'),
        ),
    ]
