# Generated by Django 5.0.3 on 2024-03-17 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0004_remove_tashxis_user_alter_tashxis_bemor'),
        ('User', '0003_remove_bemor_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tashxis',
            name='bemor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='User.bemor'),
        ),
    ]
